name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Push Msg'
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        bash ./kk.sh
        
